AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  NotionServerless

  Sample SAM Template for NotionServerless
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CompanyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: company/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        Company:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /company
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CompanyApi:
    Description: "API Gateway endpoint URL for Prod stage for Company function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/company/"
  CompanyFunction:
    Description: "Company Lambda Function ARN"
    Value: !GetAtt CompanyFunction.Arn
  CompanyFunctionIamRole:
    Description: "Implicit IAM Role created for Company function"
    Value: !GetAtt CompanyFunctionRole.Arn
